// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session08.Exercise.DAL;

namespace Session08.Exercise.DAL.Migrations
{
    [DbContext(typeof(AppDbContext1))]
    [Migration("13980213234857_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Session08.Exercise.Domain.Child01", b =>
                {
                    b.Property<int>("Child01Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("ParentId");

                    b.HasKey("Child01Id");

                    b.HasIndex("ParentId");

                    b.ToTable("child01s");
                });

            modelBuilder.Entity("Session08.Exercise.Domain.Child02", b =>
                {
                    b.Property<int>("Child02Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("ParentId");

                    b.HasKey("Child02Id");

                    b.HasIndex("ParentId")
                        .IsUnique();

                    b.ToTable("child02s");
                });

            modelBuilder.Entity("Session08.Exercise.Domain.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ParentId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Session08.Exercise.Domain.Child01", b =>
                {
                    b.HasOne("Session08.Exercise.Domain.Parent", "Parent")
                        .WithMany("Child01s")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Session08.Exercise.Domain.Child02", b =>
                {
                    b.HasOne("Session08.Exercise.Domain.Parent", "Parent")
                        .WithOne("Child02")
                        .HasForeignKey("Session08.Exercise.Domain.Child02", "ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
